openapi: "3.0.0"

info:
  $ref: ./info/index.yml

servers:
  $ref: ./servers/index.yml

tags:
  $ref: ./tags/index.yml

paths:
  $ref: ./paths/index.yml


components:
  $ref: ./components/index.yml
security:
  - ApiKeyAuth: []
