openapi: "3.0.0"

info:
  $ref: ./info/index.yml

servers:
  $ref: ./servers/index.yml

tags:
  $ref: ./tags/index.yml

paths:
  # BOOSTER endpoint
  /review_booster/send_invitation:
    post:
      $ref: ./paths/review_booster/send_invitation/post.yml
  /review_booster/invitation_status:
    get:
      $ref: ./paths/review_booster/invitation_status/get.yml
  /review_booster/search-invitation:
    get:
      $ref: ./paths/review_booster/search-invitation/get.yml

  # USER endpoints
  /user/me:
    get:
      $ref: ./paths/user/get_me.yml
  /user:
    post:
      $ref: ./paths/user/post.yml
  /user/{user_id}:
    get:
      $ref: ./paths/user/get_by_id.yml
    post:
      $ref: ./paths/user/post_update.yml
    delete:
      $ref: ./paths/user/delete.yml
  /user/search:
    get:
      $ref: ./paths/user/get_search.yml
  /user/search/count:
    get:
      $ref: ./paths/user/get_search_count.yml
  /user/{user_id}/invite:
    post:
      $ref: ./paths/user/post_invite.yml
  /user/{user_id}/businesses:
    get:
      $ref: ./paths/user/get_businesses.yml

  /authorize:
    post:
      $ref: ./paths/authorize/post.yml
  /authorize/list:
    get:
      $ref: ./paths/authorize/get.yml
  /authorize/revoke:
    post:
      $ref: ./paths/authorize/post_revoke.yml

  # REVIEWS endpoints
  /reviews:
    get:
      $ref: ./paths/reviews/get.yml
  /reviews/qualitative-evolution:
    get:
      $ref: ./paths/reviews/get_qualitative_evolution.yml
  /reviews/quantitative-evolution:
    get:
      $ref: ./paths/reviews/get_quantitative_evolution.yml
  /reviews/{review_id}/reply/edit:
    post:
      $ref: ./paths/reviews/post_reply.yml
  /reviews/{review_id}/reply/delete:
    delete:
      $ref: ./paths/reviews/delete_reply.yml

  # ORG endpoints
  /org/{org_id}:
    get:
      $ref: ./paths/organizations/get_by_id.yml
    post:
      $ref: ./paths/organizations/post_update.yml
    delete:
      $ref: ./paths/organizations/delete.yml
  /org/search:
    get:
      $ref: ./paths/organizations/get_search.yml
  /org:
    post:
      $ref: ./paths/organizations/post_create.yml

  # BUSINESS endpoints
  /business/search:
    get:
      $ref: ./paths/business/get_search.yml
  /business:
    post:
      $ref: ./paths/business/post_create.yml
  /business/connections_stats:
    get:
      $ref: ./paths/business/get_connections_stats.yml
  /business/{business_id}:
    get:
      $ref: ./paths/business/get_by_id.yml
    post:
      $ref: ./paths/business/post_update.yml
    delete:
      $ref: ./paths/business/delete.yml
  /business/{business_id}/partner_urls:
    get:
      $ref: ./paths/business/get_partner_urls.yml
  /business/{business_id}/integration_status:
    get:
      $ref: ./paths/business/get_integration_status.yml
  /business/{business_id}/subscription:
    get:
      $ref: ./paths/business/get_subscription.yml
  /business/{business_id}/additional_data:
    get:
      $ref: ./paths/business/get_additional_data.yml
    post:
      $ref: ./paths/business/post_additional_data.yml
  /business/{business_id}/subscribe:
    post:
      $ref: ./paths/business/post_subscribe.yml
  /business/{business_id}/unsubscribe:
    post:
      $ref: ./paths/business/post_unsubscribe.yml

  # CATEGORY endpoints
  /category/search:
    get:
      summary: Search categories
      tags:
        - Categories
      description: >
        This endpoint lets you search through Partoo categories.
      operationId: searchCategories
      parameters:
        - $ref: '#/components/parameters/query_category_lang'
        - $ref: '#/components/parameters/query_page'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ListResult'
                  - type: object
                    properties:
                      categories:
                        type: array
                        description: List of categories
                        items:
                          $ref: '#/components/schemas/Category'
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'
  /category/{category_id}:
    get:
      summary: Get category
      tags:
        - Categories
      description: >
        This endpoint lets you retrieve the data of a specific category.
      operationId: getCategory
      parameters:
        - in: path
          required: true
          name: category_id
          schema:
            $ref: '#/components/schemas/CategoryId'
        - $ref: '#/components/parameters/query_category_lang'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        400:
          $ref: '#/components/responses/400'
        401:
          $ref: '#/components/responses/401'

  # PRESENCE ANALYTICS endpoints
  /presence_analytics:
    get:
      $ref: ./paths/presence_analytics/get.yml
  /presence_analytics_export:
    get:
      $ref: ./paths/presence_analytics/get_export.yml

components:
  $ref: ./components/index.yml
security:
  - ApiKeyAuth: []
