version: 2
jobs:
  test_build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v1-yarn-deps-{{ checksum "yarn.lock" }}

      - run:
          name: install node dependencies
          command: |
            yarn

      - save_cache:
          key: v1-yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run:
          name: run build
          command: |
            yarn build

workflows:
  version: 2
  test_build:
    jobs:
      - test_build
